#!/bin/bash

mkdir -p TestCases/GeneralStats

make Clean
make

for instance in TestCases/Input/*.txt
do
    echo "Calcul des statistiques globales de l'instance" $instance
    output=${instance/Input/GeneralStats}
    ./Bin/MonExec $instance GeneralStats > $output
done
