#!/bin/bash

mkdir -p TestCases/Output

make Clean
make

for instance in TestCases/Input/*.txt
do
    echo "Recherche de l'instance" $instance
    output=${instance/Input/Output}
    ./Bin/MonExec $instance > $output
done
